version: '3.8'

services:
  frontend:
    image: frontend:1.0
    ports:
      - "82:80"
    depends_on:
      - backend

  backend:
    image: backend:1.0
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: root
      REDIS_HOST: redis
      REDIS_PORT: 6379

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"

volumes:
  postgres_data:  