version: '3.8'

services:
  frontend:
    build:
      context: ./MONITORING_NESTJS
      dockerfile: Dockerfile.backend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./MONITORING_REACTJS
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: monitoring_2
      REDIS_HOST: redis
      REDIS_PORT: 6379

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:  